version: '3.4'

services:
  mysql:
    image: mysql:8.0.23
    environment:
      - MYSQL_DATABASE=cravr
      - MYSQL_ROOT_PASSWORD=ece49595bois!
      - MYSQL_USER=backend
      - MYSQL_PASSWORD=ece49595bois!
    container_name: mysql_container
    restart: always
    volumes:
      - /app/database
    expose:
      - '3306'
    ports:
      - '3306:3306'
  flask:
    container_name: flask_container
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
      target: flask
    volumes:
      - /app/backend
    expose: 
      - '5000'
    ports:
      - '5000:5000'
  react:
    container_name: react_container
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: react
    volumes:
      - /frontend/node_modules
      - /frontend/package.json
      - ./frontend:/app
    expose: 
      - '3000'
    ports:
      - '3000:3000'
