version: '3.7'

services:
  mysql:
    image: mysql:8.0.23
    environment:
      - MYSQL_DATABASE=cravr
      - MYSQL_ROOT_PASSWORD=ece49595bois!
      - MYSQL_USER=backend
      - MYSQL_PASSWORD=ece49595bois!
    container_name: mysql_container
    restart: always
    volumes:
      - /app/database:/docker-entrypoint-initdb.d/:ro
    expose:
      - '3306'
    ports:
      - '3306:3306'
  flask:
    container_name: flask_container
    restart: always
    depends_on:
      - mysql
    build:
      dockerfile: Dockerfile
      context: .
      target: flask
    env_file: ./backend/.env
    volumes:
      - ./app/backend:/app
    expose: 
      - '5000'
    ports:
      - '5000:5000'
  react:
    container_name: react_container
    restart: always
    depends_on:
      - flask
    build:
      dockerfile: Dockerfile
      context: .
      target: react
    environment:
      NODE_ENV: development
    volumes:
      - /frontend/node_modules
    expose: 
      - '3000'
    ports:
      - '3000:3000'
