version: '3.4'

services:
  mysql:
    container_name: mysql_container
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./mysql
      target: mysql
    volumes:
      - /app/mysql
  flask:
    container_name: flask_container
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
      target: flask
    volumes:
      - /app/backend
    expose: 
      - '5000'
    ports:
      - '5000:5000'
  react:
    container_name: react_container
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: react
    volumes:
      - /frontend/node_modules
      - /frontend/package.json
      - ./frontend:/app
    expose: 
      - '3000'
    ports:
      - '3000:3000'
