version: '3'

services:
  mysql:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - /app/node_modules
      - ./server:/app
  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - '5000:5000'
  react:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /frontend/node_modules
      - ./frontend:/app
    expose: 
      - '3000'
    ports:
      - '3000:3000'
