name: Flask Application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
          pip install pytest
      - name: Test with pytest
        run: |
          python -m pytest
