name: Flask Application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
          pip install pytest
      - name: Test with pytest
        run: |
          python -m pytest --envfile ./backend/.env
      - name: Create SBOM
        run: |
          pip freeze > ./backend/requirements.txt
          cyclonedx-py -j -i ./backend/requirements.txt -o ./backend/flask-bom.json
      - name: Commit SBOM changes
        run: |
          git status
          git add ./backend/flask-bom.json
          git config --local user.name ${{ github.actor }}
          git commit -m "Auto updating backend SBOM"
      - name: Push SBOM to the current branch
        uses: ad-m/github-push-action@${GITHUB_REF##*/}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
