# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pass the test
      run: echo "Placeholder test passed!"

    # These will work once we have enough code to test
#     - name: Install npm dependencies
#       run: npm ci
#     - name: Build app
#       run: npm run build --if-present
#     - name: Run tests
#       run: npm test
