name: Create SBOMs

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create backend SBOM
        run: |
          pip install cyclonedx-bom
          pip freeze > ./backend/requirements.txt
          cyclonedx-py -j -i ./backend/requirements.txt -o ./backend/flask-bom.json
      - name: Commit SBOM changes
        run: |
          git status
          git add ./backend/flask-bom.json
          git config --local user.name ${{ github.actor }}
          git commit -m "Auto updating backend SBOM"
      - name: Push SBOM to the current branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
